### ISSUE TITLE
core.py crashes on currently enabled test

### ISSUE THREAD

**Issue by donuty-party** [NSCC-COGS/Aestheta#56]
Hey Kevin, do you know offhand what's going on here?

```
/content/Aestheta/Library/core.py in loadModel(name, model_dir)
    125     filename = model_dir+newest_model
    126     print(filename)
--> 127     classModel, classes = pickle.load(open(filename, 'rb'))
    128 
    129     return classModel, classes

sklearn/tree/_tree.pyx in sklearn.tree._tree.Tree.__cinit__()

ValueError: Buffer dtype mismatch, expected 'SIZE_t' but got 'int'
```

**Comment by kevinkmcguigan** [comment]
My guess is that the load is failing due to something the file not existing or perhaps the path is wrong. Perhaps if we set the python environment variables to the astheta workspace it would ensure the path is correct  - but that may not be a best practice

**Comment by kevinkmcguigan** [comment]
I dug in a bit more. This fails in a similar way when pulling things to google colab. Searching around it seems that this maybe an issue **caused by building the model on a 32-bit machine.** AND as it turns out my laptop's python version was set to 3.8.1 32! Good find as I certainly was **not using 32 bit intentionally.**

This is a good learning note to everyone - it seems we can likely add '64bit version of python' to the list of our requirements

**I will switch over to 64-bit python**, regenerate the model and close the issue if it works. Thanks again Jeff!

Relevant stack overflow post:
https://stackoverflow.com/questions/21033038/scikits-learn-randomforrest-trained-on-64bit-python-wont-open-on-32bit-python

**Comment by kevinkmcguigan** [comment]
implemented model saving/loading for 32 bit and 64 bit python
