### ISSUE TITLE
What are the limits of the usage on google free map api 

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#8]

**Comment by arraySurfer81210** [comment]
## Google Earth Engine Terms of Service
https://earthengine.google.com/terms/

### Most Relevant Sections:
1.2 Limitations on Use. Unless otherwise approved by Google in writing, Services may only be used for development, research, or educational purposes; you can use data or figures created by use of Services in research or educational publications authored by you. Services may not be used for sustained commercial purposes unless otherwise approved by Google in writing, but may be evaluated in a production environment. Applications and data created with Services may not be sold or licensed for a fee unless otherwise approved by Google in writing.

2.3 Restrictions. Customer will not, and will not allow third parties under its control to: (a) copy, modify, create a derivative work of, reverse engineer, decompile, translate, disassemble, or otherwise attempt to extract any or all of the source code of the Services (subject to Section 2.4 below and except to the extent such restriction is expressly prohibited by applicable law); (b) use the Services for High Risk Activities; (c) sublicense or distribute any or all of the Services on a standalone basis (separate from any integrated Application); (d) create multiple Applications or Accounts to simulate or act as a single Application or Account (respectively); 

4.4 Content Accessible Through Services. The Service contains some third party content (such as images, vector data, and metadata). This content is the sole responsibility of the person or organization that makes it available. Content accessible through our Service may be subject to the content owners’ intellectual property rights (for example, attribution requirements or commercial use restrictions), and, if so, you may not use it unless you are licensed to do so by the owner of that content (for example, through the owner’s terms of use) or are otherwise permitted by law. Your access to the content provided by the Services may be restricted, limited, or filtered in accordance with applicable law, regulation, and policy.

7.3 Termination for Inactivity. Google reserves the right to terminate the Services for inactivity, if, for a period exceeding 180 days, Customer has failed to access the Service.

8. Publicity. Customer is permitted to state publicly that it is a customer of the Services, consistent with the Trademark Guidelines. If Customer wants to display Google Brand Features in connection with its use of the Services, Customer must obtain written permission from Google through the process specified in the Trademark Guidelines. Google may include Customer’s name or Brand Features in a list of Google customers, online or in promotional materials. Google may also verbally reference Customer as a customer of the Services. Neither party needs approval if it is repeating a public statement that is substantially similar to a previously-approved public statement. Any use of a party’s Brand Features will inure to the benefit of the party holding Intellectual Property Rights to those Brand Features. A party may revoke the other party’s right to use its Brand Features under this Section with written notice to the other party and a reasonable period to stop the use.

**Comment by arraySurfer81210** [comment]
## API Limit Synopsis

"Free usage is limited to: “up to 25,000 map loads per day for each API” or “up to 2,500 map loads per day that have been modified using the Styled Maps feature.” Non-profits and those map applications determined by Google to be “in the public interest” are exempt from the new usage limits. "

source: 
https://northscottsdaledetailing.com/chronic-pain-rkir/a39a97-google-maps-api-usage-limits

**Comment by kevinkmcguigan** [comment]
Some good information - thanks for closing this
